### ISSUE TITLE
Error on BioPAX Validator Site with >1MB Files

### ISSUE THREAD

**Issue by cannin** [BioPAX/validator#12]
# Test Parameters 
* Validation Profile: Less Strict 
* Error Case Filter: Only Errors 
* Stop After: 1 Error 
* Report: XML 

# Input Test Files
* https://github.com/BioPAX/Paxtools/blob/master/json-converter/src/test/resources/PC2v5test-Signaling-By-BMP-Pathway-REACT_12034.2.owl (Large file, does not work)
* https://github.com/BioPAX/Paxtools/blob/master/paxtools-archetype/src/main/resources/archetype-resources/src/main/resources/biopax3-short-metabolic-pathway.owl (Small file, does work) 

# Local Jar Usage
Using latest version here: https://sourceforge.net/projects/biopax/files//paxtools/

    java -jar paxtools-5.1.0.jar validate PC2v5test-Signaling-By-BMP-Pathway-REACT_12034.2.owl report.xml xml only-errors maxerrors=1 notstrict

## Error Message
    #logback.classic pattern: %d %-5level [%thread] %logger{25} - %msg%n
    2019-11-13 08:25:19,316 INFO  [main] o.b.p.c.BiopaxValidatorClient - BioPAX Validator location: http://biopax.baderlab.org/check.html
    2019-11-13 08:25:26,021 ERROR [main] o.b.paxtools.PaxtoolsMain - Unable to check with the biopax-validator web service:
     org.apache.http.client.HttpResponseException:
     Fall-back: trying to parse the file(s) with paxtools (up to the first syntax error in each file)...

    org.apache.http.client.HttpResponseException:
    	at org.apache.http.client.fluent.ContentResponseHandler.handleResponse(ContentResponseHandler.java:47) ~[paxtools-5.1.0.jar:na]
    	at org.apache.http.client.fluent.ContentResponseHandler.handleResponse(ContentResponseHandler.java:40) ~[paxtools-5.1.0.jar:na]
    	at org.apache.http.client.fluent.Response.handleResponse(Response.java:85) ~[paxtools-5.1.0.jar:na]
    	at org.apache.http.client.fluent.Response.returnContent(Response.java:92) ~[paxtools-5.1.0.jar:na]
    	at org.biopax.paxtools.client.BiopaxValidatorClient.validate(BiopaxValidatorClient.java:176) ~[paxtools-5.1.0.jar:na]
    	at org.biopax.paxtools.PaxtoolsMain.validate(PaxtoolsMain.java:374) ~[paxtools-5.1.0.jar:na]
    	at org.biopax.paxtools.Main$Command$4.run(Main.java:72) ~[paxtools-5.1.0.jar:na]
    	at org.biopax.paxtools.Main.main(Main.java:22) ~[paxtools-5.1.0.jar:na]

# Online Validator
Only "Error" is returned while using the online validator. 

![Screen Shot 2019-11-12 at 10 32 50 PM](https://user-images.githubusercontent.com/790284/68766701-57ffee80-05ed-11ea-8ceb-604260dbcf21.jpg)

**Comment by cannin** [comment]
The standalone validator (https://sourceforge.net/projects/biopax/files/validator/) should work. The command I used for a 1.4MB BioPAX file:

    sh validate.sh PC2v5test-Signaling-By-BMP-Pathway-REACT_12034.2.owl report.xml --out-format=xml --profile=notstrict

# Comments
* This did not seem to work on Java 11, but Java 8 (1.8.0.232) worked.
On OSX, you can do this:
https://www.dhiller.de/2019/01/06/setup-multiple-jdks-with-jenv-and-adoptopenjdk.html
* I increased the amount of RAM in validate.sh with -Xmx8g This might
not be necessary.
* It took about 8 minutes to run

**Comment by IgorRodchenkov** [comment]
Standalone biopax-validator is better use to validate multiple large files (a directory) at once (init may take ~5-10 minutes due to parsing OBO files, etc.)

**Comment by IgorRodchenkov** [comment]
@cannin , @gbader I fixed this issue - a special configuration was missing after the last code upgrade to Spring Boot 2 web app. So I configured the app's (_multipartResolver_ bean and properties), and one can now validate large files again (up to 100Mb).
