### ISSUE TITLE
BioPAX validator raises java.lang.reflect.InaccessibleObjectException

### ISSUE THREAD

**Issue by quirinmanz** [BioPAX/validator#31]
Dear BioPAX Validator Team,

Thanks for the framework!

I am having trouble validating owl files after doing the following:

I downloaded the zip from Sourceforge and unpacked it.
After changing to the distr directory, I get:
```
distr-5.1.0$ sh validate.sh file:sampleData/biopax3-genetic-interaction.owl 
your JAVA_HOME=/path/to/env/lib/jvm
openjdk version "17.0.8-internal" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17.0.8-internal+0-adhoc..src, mixed mode, sharing)
Running BioPAX Validator...
#logback.classic pattern: %d %-5level [%thread] %logger{25} - %msg%n
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @4493d195
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
...
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at org.biopax.validator.Main.main(Main.java:79)
```
This also happens with Java 20:
```
distr-5.1.0$ sh validate.sh file:sampleData/biopax3-genetic-interaction.owl 
your JAVA_HOME=/path/to/env/lib/jvm
openjdk version "20.0.2-internal" 2023-07-18
OpenJDK Runtime Environment (build 20.0.2-internal-adhoc..src)
OpenJDK 64-Bit Server VM (build 20.0.2-internal-adhoc..src, mixed mode, sharing)
Running BioPAX Validator...
#logback.classic pattern: %d %-5level [%thread] %logger{25} - %msg%n
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @480bdb19
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
...
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at org.biopax.validator.Main.main(Main.java:79)
```

The same happens regardless of input or parameters, so I suspect something is going wrong very early.
Could you help me with this?

Best,
Quirin

**Comment by IgorRodchenkov** [comment]
Hi Quirin,

Please, just define:

export JDK_JAVA_OPTIONS=--add-opens java.base/java.lang=ALL-UNNAMED
--add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/
sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED

in the environment where you run validate.sh (or in that script itself).
This is not a bug.

**Comment by quirinmanz** [comment]
I see that there is this comment inside the script itself as well. Sorry, I must've missed it. 
Thanks for the quick help

**Comment by IgorRodchenkov** [comment]
See/try also the latest validator snapshot (v6.0.0) at https://oss.sonatype.org/content/groups/public/org/biopax/validator/distr/6.0.0-SNAPSHOT/ 
(the normalizer there uses bioregistry.io based bio collection/identifiers resolver)
